apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goblin
resources:
  - postgres.yaml
configMapGenerator:
  - name: goblin-postgres-init
    files:
      - init-database.sh
  - name: goblin-postgres-config
    files:
      - pg_hba.conf
      - pg_ident.conf
      - start-postgres.sh
