// Generate selected Codex App Server System.Text.Json POCOs from checked-in schemas.
// Run from the repository root: dotnet run --file backend/scripts/GenerateProtocol.cs
#:property Nullable=enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

return ProtocolGeneratorApp.Run(args);

internal static class ProtocolGeneratorApp
{
    internal static int Run(string[] args)
    {
        if (args.Any(arg => arg is not ("--check" or "--self-test")))
        {
            Console.Error.WriteLine("Usage: dotnet run --file backend/scripts/GenerateProtocol.cs -- [--check] [--self-test]");
            return 2;
        }

        try
        {
            if (args.Contains("--self-test"))
            {
                ProtocolGeneratorTests.Run();
                Console.WriteLine("Protocol generator tests passed.");
            }

            if (args.Length == 1 && args[0] == "--self-test")
                return 0;

            var backend = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(ScriptPath())!, ".."));
            var schemas = Path.Combine(backend, "schemas", "codex");
            var output = Path.Combine(backend, "src", "Goblin.Protocol", "Generated");
            var generator = new ProtocolGenerator(schemas, File.ReadAllText(Path.Combine(schemas, "selection.json")));
            return WriteOrCheck(generator.Generate(), output, args.Contains("--check"));
        }
        catch (Exception error)
        {
            Console.Error.WriteLine(error.Message);
            return 1;
        }
    }

    private static string ScriptPath([CallerFilePath] string path = "") => path;

    private static int WriteOrCheck(Dictionary<string, string> files, string directory, bool check)
    {
        var current = Directory.Exists(directory)
            ? Directory.EnumerateFiles(directory, "*", SearchOption.TopDirectoryOnly)
                .ToDictionary(path => Path.GetFileName(path)!, path => path, StringComparer.Ordinal)
            : new Dictionary<string, string>(StringComparer.Ordinal);
        var changed = files.Where(file => !current.TryGetValue(file.Key, out var path)
                || File.ReadAllText(path) != file.Value)
            .Select(file => file.Key).Order(StringComparer.Ordinal).ToList();
        var stale = current.Keys.Except(files.Keys, StringComparer.Ordinal).Order(StringComparer.Ordinal).ToList();

        if (check)
        {
            if (changed.Count > 0 || stale.Count > 0)
            {
                Console.Error.WriteLine("Protocol generation is out of date: " + string.Join(", ", changed.Concat(stale)));
                return 1;
            }
            Console.WriteLine($"Protocol generation is current ({files.Count - 1} generated model files).");
            return 0;
        }

        Directory.CreateDirectory(directory);
        foreach (var name in stale)
            File.Delete(current[name]);
        foreach (var (name, content) in files)
            File.WriteAllText(Path.Combine(directory, name), content);
        Console.WriteLine($"Generated {files.Count - 1} selected Codex model files.");
        return 0;
    }
}

internal sealed class ProtocolGenerator
{
    private const string Header = "// <auto-generated />\n"
        + "// Source: backend/schemas/codex; regenerate with dotnet run --file backend/scripts/GenerateProtocol.cs\n"
        + "#nullable enable\nusing System;\nusing System.Collections.Generic;\nusing System.Text.Json;\n"
        + "using System.Text.Json.Serialization;\n\nnamespace Goblin.Protocol;\n\n";
    private static readonly HashSet<string> Metadata = ["$schema", "title", "description", "default"];
    private readonly string _schemaDirectory;
    private readonly JsonObject? _selection;
    private readonly string? _selectionHash;
    private readonly Dictionary<string, JsonNode> _schemas = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> _refs = new(StringComparer.Ordinal);
    private readonly HashSet<string> _allNamed;
    private readonly HashSet<string> _named;
    private readonly HashSet<string> _selectedTypes = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string?> _parents = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> _generated = new(StringComparer.Ordinal);
    private readonly HashSet<string> _generating = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> _aliases = new(StringComparer.Ordinal);
    private readonly string _sourceHash;
    private readonly int _schemaFiles;

    internal ProtocolGenerator(string schemaDirectory, string? selectionJson)
    {
        _schemaDirectory = schemaDirectory;
        var aggregatePath = Path.Combine(schemaDirectory, "codex_app_server_protocol.schemas.json");
        var definitions = AsObject(Parse(File.ReadAllText(aggregatePath))["definitions"]);
        foreach (var (key, value) in definitions)
        {
            if (key == "v2")
            {
                foreach (var (name, schema) in AsObject(value))
                    AddNamed(name, schema!, "#/definitions/v2/" + name);
            }
            else
                AddNamed(key, value!, "#/definitions/" + key);
        }
        _allNamed = _schemas.Keys.ToHashSet(StringComparer.Ordinal);
        _named = _schemas.Keys.ToHashSet(StringComparer.Ordinal);
        VerifyIndividualSchemas();
        var paths = SchemaPaths().ToList();
        _schemaFiles = paths.Count;
        using (var hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256))
        {
            foreach (var path in paths)
            {
                hash.AppendData(Encoding.UTF8.GetBytes(Path.GetRelativePath(schemaDirectory, path).Replace('\\', '/')));
                hash.AppendData([0]);
                hash.AppendData(File.ReadAllBytes(path));
                hash.AppendData([0]);
            }
            _sourceHash = Convert.ToHexStringLower(hash.GetHashAndReset());
        }
        if (selectionJson is not null)
        {
            _selection = AsObject(Parse(selectionJson));
            _selectionHash = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(selectionJson)));
            ApplySelection(_selection);
        }
    }

    private static JsonNode Parse(string text) => JsonNode.Parse(text) ?? throw new InvalidOperationException("Expected JSON value.");
    private static JsonObject AsObject(JsonNode? node) => node as JsonObject ?? throw new InvalidOperationException("Expected JSON object.");
    private static JsonArray AsArray(JsonNode? node) => node as JsonArray ?? throw new InvalidOperationException("Expected JSON array.");
    private static JsonNode? Get(JsonNode? node, string key) => node is JsonObject obj && obj.TryGetPropertyValue(key, out var value) ? value : null;
    private static bool Has(JsonNode? node, string key) => node is JsonObject obj && obj.ContainsKey(key);
    private static string? Str(JsonNode? node) => node is JsonValue value && value.TryGetValue<string>(out var text) ? text : null;
    private static bool Bool(JsonNode? node, bool expected) => node is JsonValue value && value.TryGetValue<bool>(out var actual) && actual == expected;
    private static IEnumerable<string> Strings(JsonNode? node) => node is JsonArray array ? array.Select(value => Str(value) ?? throw new InvalidOperationException("Expected string array.")) : [];
    private static JsonNode? Clone(JsonNode? node) => node?.DeepClone();
    private static string Literal(string text) => JsonValue.Create(text)!.ToJsonString();
    private static JsonNode? Normalize(JsonNode? node)
    {
        if (node is JsonArray array)
            return new JsonArray(array.Select(Normalize).ToArray());
        if (node is JsonObject obj)
        {
            var result = new JsonObject();
            foreach (var (key, value) in obj.OrderBy(pair => pair.Key, StringComparer.Ordinal))
            {
                if (Metadata.Contains(key))
                    continue;
                result[key] = key == "$ref" ? JsonValue.Create(Str(value)?.Split('/')[^1]) : Normalize(value);
            }
            return result;
        }
        return Clone(node);
    }
    private static bool SemanticEqual(JsonNode? left, JsonNode? right) => JsonNode.DeepEquals(Normalize(left), Normalize(right));
    private static bool IsEmptySemantic(JsonNode? node) => node is JsonObject && AsObject(Normalize(node)).Count == 0;

    private void AddNamed(string name, JsonNode schema, string reference)
    {
        if (_schemas.TryGetValue(name, out var previous) && !SemanticEqual(previous, schema))
            throw new InvalidOperationException("Conflicting protocol definition: " + name);
        _schemas[name] = schema;
        _refs[reference] = name;
    }

    private IEnumerable<string> SchemaPaths() => Directory.EnumerateFiles(_schemaDirectory, "*.json", SearchOption.AllDirectories)
        .Where(path => Path.GetFileName(path) != "selection.json")
        .OrderBy(path => Path.GetRelativePath(_schemaDirectory, path).Replace('\\', '/'), StringComparer.Ordinal);

    private void VerifyIndividualSchemas()
    {
        foreach (var path in SchemaPaths())
        {
            var filename = Path.GetFileName(path);
            if (filename == "codex_app_server_protocol.schemas.json")
                continue;
            var document = AsObject(Parse(File.ReadAllText(path)));
            if (filename == "codex_app_server_protocol.v2.schemas.json")
            {
                foreach (var (name, value) in AsObject(document["definitions"]))
                    Verify(name, value, path);
            }
            else
            {
                var name = Path.GetFileNameWithoutExtension(path);
                var main = new JsonObject();
                foreach (var (key, value) in document)
                    if (key != "definitions") main[key] = Clone(value);
                Verify(name, main, path);
                if (Has(document, "definitions"))
                    foreach (var (localName, value) in AsObject(document["definitions"]))
                        Verify(localName, value, path);
            }
        }
    }

    private void Verify(string name, JsonNode? value, string path)
    {
        if (!_schemas.TryGetValue(name, out var aggregate) || !SemanticEqual(value, aggregate))
            throw new InvalidOperationException($"Aggregate and individual schemas disagree: {Path.GetRelativePath(Path.GetDirectoryName(_schemaDirectory)!, path).Replace('\\', '/')}: {name}");
    }

    internal static string Pascal(string value)
    {
        value = Regex.Replace(value, @"v\d+::", "");
        var result = string.Concat(Regex.Split(value, "[^a-zA-Z0-9]+", RegexOptions.None)
            .Where(part => part.Length > 0)
            .Select(part => part.Any(char.IsLetter) && part.Where(char.IsLetter).All(char.IsUpper)
                ? char.ToUpperInvariant(part[0]) + part[1..].ToLowerInvariant()
                : char.ToUpperInvariant(part[0]) + part[1..]));
        return result.Length == 0 || char.IsDigit(result[0]) ? "Value" + result : result;
    }

    private static List<string> NameWords(string value) => Regex.Matches(Pascal(value), @"[A-Z]+(?=[A-Z][a-z]|[0-9]|$)|[A-Z]?[a-z]+|[0-9]+")
        .Select(match => match.Value).ToList();

    internal static string CombineTypeNames(string first, string second)
    {
        var left = NameWords(first);
        var right = NameWords(second);
        var prefix = 0;
        while (prefix < Math.Min(left.Count, right.Count) && left[prefix] == right[prefix]) prefix++;
        var suffix = 0;
        while (suffix < Math.Min(left.Count, right.Count) - prefix && left[^(suffix + 1)] == right[^(suffix + 1)]) suffix++;
        return string.Concat(left.Take(left.Count - suffix).Concat(right.Skip(prefix).Take(right.Count - prefix - suffix))
            .Concat(suffix == 0 ? [] : left.Skip(left.Count - suffix)));
    }

    internal static string VariantTypeName(string label, string parent, bool wrapped = false)
    {
        var name = CombineTypeNames(label, parent);
        return name == parent || wrapped && name == label ? name + "Variant" : name;
    }

    internal static string NestedTypeName(string owner, string member, JsonNode? schema)
    {
        (_, schema) = NullableSchema(schema);
        if (Has(schema, "title")) return owner + member;
        var ownerWords = NameWords(owner);
        var memberWords = NameWords(member);
        if (Str(Get(schema, "type")) == "object" && memberWords.Count > 1
            && Enumerable.Range(0, Math.Max(0, ownerWords.Count - memberWords.Count + 1))
                .Any(start => ownerWords.Skip(start).Take(memberWords.Count).SequenceEqual(memberWords)))
            return member + "Details";
        var name = CombineTypeNames(owner, member);
        return name == owner ? owner + member : name;
    }

    private static Dictionary<string, object> FieldTree(JsonNode? paths, string context)
    {
        // A dictionary's empty key marks a selected leaf. Its other keys are nested fields.
        var root = new Dictionary<string, object>(StringComparer.Ordinal);
        if (paths is not JsonArray values || values.Any(value => Str(value) is null or ""))
            throw new InvalidOperationException("Expected field paths at " + context);
        foreach (var pathNode in values)
        {
            var path = Str(pathNode)!;
            var parts = path.Split('.');
            if (parts.Any(part => part.Length == 0))
                throw new InvalidOperationException($"Invalid field path at {context}: {path}");
            var current = root;
            foreach (var part in parts)
            {
                if (current.ContainsKey(""))
                    throw new InvalidOperationException($"Field path extends a selected value at {context}: {path}");
                if (!current.TryGetValue(part, out var child))
                    current[part] = child = new Dictionary<string, object>(StringComparer.Ordinal);
                current = (Dictionary<string, object>)child;
            }
            if (current.Count > 0)
                throw new InvalidOperationException($"Field path selects a parent of another path at {context}: {path}");
            current[""] = new object();
        }
        return root;
    }

    private JsonNode SelectFields(JsonNode schema, JsonNode? paths, string context)
    {
        return SelectNested(schema, FieldTree(paths, context), context);
    }

    private JsonNode SelectNested(JsonNode schema, Dictionary<string, object> tree, string context)
    {
        if (schema is not JsonObject original)
            throw new InvalidOperationException("Field path enters a non-object at " + context);
        if (Has(schema, "$ref"))
            throw new InvalidOperationException("Select referenced definitions separately at " + context);
        if (Has(schema, "allOf"))
        {
            var branches = AsArray(schema["allOf"]);
            if (branches.Count != 1)
                throw new InvalidOperationException("Unsupported multi-branch allOf at " + context);
            var result = (JsonObject)original.DeepClone();
            result["allOf"] = new JsonArray(SelectNested(branches[0]!, tree, context));
            return result;
        }
        foreach (var key in new[] { "anyOf", "oneOf" })
        {
            if (Get(schema, key) is not JsonArray branches || branches.Count != 2) continue;
            var nonnull = Enumerable.Range(0, 2).Where(index => Str(Get(branches[index], "type")) != "null").ToList();
            if (nonnull.Count != 1) continue;
            var result = (JsonObject)original.DeepClone();
            var selected = (JsonArray)branches.DeepClone();
            selected[nonnull[0]] = SelectNested(branches[nonnull[0]]!, tree, context);
            result[key] = selected;
            return result;
        }
        if (Str(Get(schema, "type")) == "array")
        {
            var result = (JsonObject)original.DeepClone();
            result["items"] = SelectNested(schema["items"]!, tree, context + "[]");
            return result;
        }
        if (Str(Get(schema, "type")) != "object")
            throw new InvalidOperationException("Field path enters a non-object at " + context);
        var properties = Get(schema, "properties") as JsonObject ?? new JsonObject();
        var missing = tree.Keys.Except(properties.Select(pair => pair.Key), StringComparer.Ordinal).Order(StringComparer.Ordinal).ToList();
        if (missing.Count > 0)
            throw new InvalidOperationException($"Unknown selected field at {context}: {string.Join(", ", missing)}");
        var selectedProperties = new JsonObject();
        foreach (var (name, value) in properties)
        {
            if (!tree.TryGetValue(name, out var childrenObject)) continue;
            var children = (Dictionary<string, object>)childrenObject;
            selectedProperties[name] = children.ContainsKey("") ? Clone(value)
                : SelectNested(value!, children, context + "." + name);
        }
        if (Bool(Get(schema, "additionalProperties"), false) && selectedProperties.Count != properties.Count)
            throw new InvalidOperationException("Closed Codex object needs all fields selected at " + context);
        var output = (JsonObject)original.DeepClone();
        output["properties"] = selectedProperties;
        output["required"] = new JsonArray(Strings(Get(schema, "required"))
            .Where(selectedProperties.ContainsKey).Select(name => (JsonNode?)JsonValue.Create(name)).ToArray());
        return output;
    }

    private static string BranchKey(JsonNode branch, string? discriminator)
    {
        if (discriminator is not null)
            return Strings(Get(Get(Get(branch, "properties"), discriminator), "enum")).First();
        if (Str(Get(branch, "title")) is { } title) return title;
        if (Str(Get(branch, "type")) != "object") return Str(Get(branch, "type")) ?? "value";
        var properties = AsObject(Get(branch, "properties"));
        if (properties.Count == 1) return properties.First().Key;
        throw new InvalidOperationException("An untagged union branch needs a title or a single property");
    }

    private JsonNode SelectUnion(JsonNode schema, JsonNode? spec, string context)
    {
        if (spec is not JsonObject specification || specification.Count != 1 || !Has(spec, "variants")
            || Get(spec, "variants") is not JsonObject choices)
            throw new InvalidOperationException("Expected union variants at " + context);
        var key = Has(schema, "oneOf") ? "oneOf" : "anyOf";
        var branches = AsArray(Get(schema, key));
        var discriminator = Discriminator(branches);
        var keyed = new Dictionary<string, JsonNode>(StringComparer.Ordinal);
        foreach (var branch in branches)
            if (!keyed.TryAdd(BranchKey(branch!, discriminator), branch!))
                throw new InvalidOperationException("Duplicate union branch key at " + context);
        var missing = choices.Select(pair => pair.Key).Except(keyed.Keys, StringComparer.Ordinal)
            .Where(name => name != "*").Order(StringComparer.Ordinal).ToList();
        if (missing.Count > 0)
            throw new InvalidOperationException($"Unknown selected variant at {context}: {string.Join(", ", missing)}");
        var selected = new JsonArray();
        foreach (var (name, branch) in keyed)
        {
            if (!choices.TryGetPropertyValue(name, out var paths) && !choices.TryGetPropertyValue("*", out paths)) continue;
            if (Str(Get(branch, "type")) == "object")
            {
                if (paths is not JsonArray fieldPaths)
                    throw new InvalidOperationException($"Expected field paths at {context}.{name}");
                var fields = (JsonArray)fieldPaths.DeepClone();
                if (discriminator is not null && !Strings(fields).Contains(discriminator)) fields.Add((JsonNode)JsonValue.Create(discriminator)!);
                selected.Add(SelectFields(branch, fields, context + "." + name));
            }
            else if (paths is JsonArray array && array.Count == 0)
                selected.Add(branch.DeepClone());
            else
                throw new InvalidOperationException($"Scalar union variant cannot select fields at {context}.{name}");
        }
        if (selected.Count == 0)
            throw new InvalidOperationException("No union variants selected at " + context);
        var output = (JsonObject)schema.DeepClone();
        output[key] = selected;
        output["properties"] = new JsonObject();
        output["required"] = new JsonArray();
        return output;
    }

    private void ApplySelection(JsonObject selection)
    {
        if (selection.Count != 2 || !Has(selection, "roots") || !Has(selection, "types"))
            throw new InvalidOperationException("Codex selection needs roots and types");
        if (Get(selection, "roots") is not JsonArray roots || Get(selection, "types") is not JsonObject types)
            throw new InvalidOperationException("Invalid Codex selection roots or types");
        var rootNames = Strings(roots).ToList();
        if (rootNames.Count != rootNames.Distinct(StringComparer.Ordinal).Count())
            throw new InvalidOperationException("Invalid Codex selection roots or types");
        var missing = rootNames.Concat(types.Select(pair => pair.Key)).Except(_allNamed, StringComparer.Ordinal)
            .Order(StringComparer.Ordinal).ToList();
        if (missing.Count > 0)
            throw new InvalidOperationException("Unknown selected Codex type: " + string.Join(", ", missing));
        foreach (var (name, spec) in types)
        {
            var schema = _schemas[name];
            _schemas[name] = Has(schema, "oneOf") || Has(schema, "anyOf")
                ? SelectUnion(schema, spec, name) : SelectFields(schema, spec, name);
            _selectedTypes.Add(name);
        }
        _named.Clear();
        _named.UnionWith(rootNames);
    }

    private static (bool Nullable, JsonNode? Schema) NullableSchema(JsonNode? schema)
    {
        while (Get(schema, "allOf") is JsonArray allOf)
        {
            if (allOf.Count != 1) throw new InvalidOperationException("Unsupported multi-branch allOf");
            schema = allOf[0];
        }
        if (Bool(schema, true) || IsEmptySemantic(schema)) return (false, schema);
        if (Get(schema, "type") is JsonArray types)
        {
            var typeNames = Strings(types).ToList();
            if (typeNames.Count != 2 || !typeNames.Contains("null"))
                throw new InvalidOperationException("Unsupported type union: " + types.ToJsonString());
            var copy = (JsonObject)schema!.DeepClone();
            copy["type"] = typeNames.Single(name => name != "null");
            return (true, copy);
        }
        foreach (var key in new[] { "anyOf", "oneOf" })
        {
            if (Get(schema, key) is not JsonArray branches || branches.Count != 2) continue;
            var nonnull = branches.Where(branch => Str(Get(branch, "type")) != "null").ToList();
            if (nonnull.Count == 1) return (true, nonnull[0]);
        }
        return (false, schema);
    }

    private static List<string>? EnumValues(JsonNode? schema)
    {
        while (Get(schema, "allOf") is JsonArray allOf)
        {
            if (allOf.Count != 1) throw new InvalidOperationException("Unsupported multi-branch allOf");
            schema = allOf[0];
        }
        if (Has(schema, "enum") && Str(Get(schema, "type")) == "string")
            return Strings(Get(schema, "enum")).ToList();
        var branches = Get(schema, "oneOf") as JsonArray ?? Get(schema, "anyOf") as JsonArray;
        return branches is not null && branches.All(branch => Str(Get(branch, "type")) == "string" && Has(branch, "enum"))
            ? branches.SelectMany(branch => Strings(Get(branch, "enum"))).ToList() : null;
    }

    private string Register(string suggestedName, JsonNode schema, string? parent = null)
    {
        var name = Pascal(suggestedName);
        if (_schemas.ContainsKey(name))
        {
            if (SemanticEqual(_schemas[name], schema) && ParentMatches(name, parent)) return name;
            var suffix = 2;
            while (_schemas.ContainsKey(name + suffix))
            {
                if (SemanticEqual(_schemas[name + suffix], schema) && ParentMatches(name + suffix, parent))
                    return name + suffix;
                suffix++;
            }
            name += suffix;
        }
        _schemas[name] = schema;
        _parents[name] = parent;
        return name;
    }

    private bool ParentMatches(string name, string? parent) =>
        (_parents.TryGetValue(name, out var existing) ? existing : null) == parent;

    private string TypeName(JsonNode? schema, string hint)
    {
        var (nullable, value) = NullableSchema(schema);
        string name;
        if (Bool(value, true) || IsEmptySemantic(value)) name = "JsonElement";
        else if (value is not JsonObject) throw new InvalidOperationException("Unsupported schema at " + hint);
        else if (Str(Get(value, "$ref")) is { } reference)
        {
            if (!_refs.TryGetValue(reference, out var referenced))
                throw new InvalidOperationException($"Unresolved reference at {hint}: {reference}");
            name = Emit(referenced);
        }
        else if (EnumValues(value) is not null || Has(value, "oneOf") || Has(value, "anyOf"))
            name = Emit(Register(hint, value));
        else
        {
            name = Str(Get(value, "type")) switch
            {
                "string" => "string",
                "boolean" => "bool",
                "null" => "ProtocolNull",
                "integer" => Str(Get(value, "format")) switch
                {
                    "int64" or null => "long",
                    "int32" => "int",
                    "uint64" or "uint" => "ulong",
                    "uint32" => "uint",
                    "uint16" => "ushort",
                    _ => throw new InvalidOperationException("Unknown integer format at " + hint),
                },
                "number" => "double",
                "array" => $"List<{TypeName(Get(value, "items"), hint + "Item")}>",
                "object" when !Has(value, "properties") && Has(value, "additionalProperties")
                    && !Bool(Get(value, "additionalProperties"), false)
                    => $"Dictionary<string, {TypeName(Get(value, "additionalProperties"), hint + "Value")}>",
                "object" => Emit(Register(hint, value)),
                _ => throw new InvalidOperationException("Unsupported schema at " + hint),
            };
        }
        return nullable && !name.EndsWith('?') ? name + "?" : name;
    }

    private string Emit(string name)
    {
        if (_selection is not null && name != "RequestId" && _allNamed.Contains(name) && !_selectedTypes.Contains(name))
        {
            var selected = _schemas[name];
            if (Str(Get(selected, "type")) == "object"
                || (Has(selected, "oneOf") || Has(selected, "anyOf")) && EnumValues(selected) is null)
                throw new InvalidOperationException("Referenced Codex type lacks a selection: " + name);
        }
        if (_aliases.TryGetValue(name, out var existingAlias)) return existingAlias;
        if (_generated.ContainsKey(name) || _generating.Contains(name)) return name;
        var (nullable, schema) = NullableSchema(_schemas[name]);
        _generating.Add(name);
        if (nullable)
        {
            var alias = TypeName(schema, name + "Value");
            _aliases[name] = alias.EndsWith('?') ? alias : alias + "?";
            _generating.Remove(name);
            return _aliases[name];
        }
        if (name == "RequestId")
        {
            var expected = Parse("""{"anyOf":[{"type":"string"},{"format":"int64","type":"integer"}]}""");
            if (!SemanticEqual(schema, expected))
                throw new InvalidOperationException("RequestId schema changed; update its scalar union representation");
            _generated[name] = RequestIdBody;
        }
        else if (EnumValues(schema) is { } values) _generated[name] = EnumBody(name, values);
        else if (Has(schema, "oneOf") || Has(schema, "anyOf")) _generated[name] = UnionBody(name, schema!);
        else if (Str(Get(schema, "type")) == "object") _generated[name] = ObjectBody(name, schema!);
        else
        {
            var alias = TypeName(schema, name);
            _aliases[name] = alias;
            _generating.Remove(name);
            return alias;
        }
        _generating.Remove(name);
        return name;
    }

    private static string EnumBody(string name, List<string> values)
    {
        if (values.Count != values.Distinct(StringComparer.Ordinal).Count())
            throw new InvalidOperationException("Duplicate enum variants in " + name);
        var names = new HashSet<string>(StringComparer.Ordinal);
        var lines = new List<string> { $"[JsonConverter(typeof(ProtocolStringEnumConverter<{name}>))]", $"public enum {name}", "{" };
        foreach (var value in values)
        {
            var member = Pascal(value);
            if (!names.Add(member)) throw new InvalidOperationException($"Enum member collision in {name}: {value}");
            lines.Add($"    [JsonStringEnumMemberName({Literal(value)})]");
            lines.Add($"    {member},");
        }
        lines.Add("}");
        return string.Join('\n', lines);
    }

    private List<string> Properties(string name, JsonNode schema, string? discriminator = null, bool inherited = false)
    {
        var lines = new List<string>();
        var properties = Get(schema, "properties") as JsonObject;
        if (properties is not null)
        foreach (var (key, value) in properties)
        {
            var prop = Pascal(key);
            if (prop == name) prop += "Value";
            var required = Strings(Get(schema, "required")).Contains(key);
            lines.Add($"    [JsonPropertyName({Literal(key)})]");
            if (discriminator == key)
            {
                var constant = Strings(Get(value, "enum")).First();
                lines.Add("    [JsonRequired]");
                lines.Add($"    public {(inherited ? "override " : "")}string {prop}");
                lines.Add("    {");
                lines.Add($"        get => {Literal(constant)};");
                lines.Add("        init");
                lines.Add("        {");
                lines.Add($"            if (value != {Literal(constant)})");
                lines.Add($"                throw new JsonException({Literal("Expected " + key + " discriminator " + constant + ".")});");
                lines.Add("        }");
                lines.Add("    }");
                lines.Add("");
                continue;
            }
            var typeName = TypeName(value, NestedTypeName(name, prop, value));
            if (required) lines.Add("    [JsonRequired]");
            else
            {
                if (!typeName.EndsWith('?')) typeName += "?";
                lines.Add("    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]");
            }
            lines.Add($"    public {(required ? "required " : "")}{typeName} {prop} {{ get; init; }}");
            lines.Add("");
        }
        if (Bool(Get(schema, "additionalProperties"), true))
        {
            lines.Add("    [JsonExtensionData]");
            lines.Add("    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }");
            lines.Add("");
        }
        return lines;
    }

    private string ObjectBody(string name, JsonNode schema, string? parent = null, string? discriminator = null)
    {
        var lines = new List<string>();
        if (Bool(Get(schema, "additionalProperties"), false))
            lines.Add("[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]");
        lines.Add($"public sealed class {name}" + (parent is null ? "" : $" : {parent}"));
        lines.Add("{");
        lines.AddRange(Properties(name, schema, discriminator, parent is not null));
        lines.Add("}");
        return string.Join('\n', lines);
    }

    private static string? Discriminator(JsonArray branches)
    {
        foreach (var key in new[] { "type", "method", "kind", "mode", "handlerType" })
        {
            var values = new List<string>();
            foreach (var branch in branches)
            {
                var enums = Strings(Get(Get(Get(branch, "properties"), key), "enum")).ToList();
                if (enums.Count != 1 || !Strings(Get(branch, "required")).Contains(key)) break;
                values.Add(enums[0]);
            }
            if (values.Count == branches.Count && values.Distinct(StringComparer.Ordinal).Count() == values.Count)
                return key;
        }
        return null;
    }

    private string UnionBody(string name, JsonNode schema)
    {
        var branches = AsArray(Get(schema, "oneOf") ?? Get(schema, "anyOf"));
        var discriminator = Discriminator(branches);
        var lines = new List<string>
        {
            $"[JsonConverter(typeof({name}JsonConverter))]",
            $"public abstract class {name}",
            "{",
        };
        if (discriminator is not null)
        {
            lines.Add($"    [JsonPropertyName({Literal(discriminator)})]");
            lines.Add($"    public abstract string {Pascal(discriminator)} {{ get; init; }}");
            lines.Add("");
            if (discriminator == "method")
            {
                var methods = branches.Select(branch => Strings(Get(Get(Get(branch, "properties"), "method"), "enum")).First()).ToList();
                lines.Add("    public static bool IsKnownMethod(string method) => method is");
                for (var index = 0; index < methods.Count; index++)
                    lines.Add($"        {Literal(methods[index])}" + (index < methods.Count - 1 ? " or" : ";"));
                lines.Add("");
            }
        }
        lines.AddRange(Properties(name, schema));
        var variants = new List<ProtocolVariant>();
        for (var index = 0; index < branches.Count; index++)
        {
            var branch = branches[index]!;
            if (discriminator is not null)
            {
                var value = Strings(Get(Get(Get(branch, "properties"), discriminator), "enum")).First();
                var hint = Has(branch, "title") ? Pascal(value) + name : VariantTypeName(Pascal(value), name);
                var variant = Register(hint, branch, name);
                _generated[variant] = ObjectBody(variant, branch, name, discriminator);
                variants.Add(new ProtocolVariant(variant, variant, false, value));
            }
            else if (Str(Get(branch, "type")) == "object")
            {
                var rawName = Str(Get(branch, "title"));
                if (rawName is null)
                {
                    var required = Strings(Get(branch, "required")).ToList();
                    rawName = VariantTypeName(required.Count > 0 ? Pascal(required[0]) : $"Variant{index + 1}", name);
                }
                var variant = Register(rawName, branch, name);
                _generated[variant] = ObjectBody(variant, branch, name);
                variants.Add(new ProtocolVariant(variant, variant, false, null));
            }
            else
            {
                var enumValues = EnumValues(branch);
                var inner = TypeName(branch, name + (enumValues is not null ? "Value" : $"Variant{index + 1}Value"));
                var label = enumValues is not null || inner == "string" ? "String"
                    : inner.StartsWith("List<", StringComparison.Ordinal) ? "Array" : Pascal(inner);
                var variant = Register(VariantTypeName(label, name, true), new JsonObject
                {
                    ["type"] = "object",
                    ["properties"] = new JsonObject { ["value"] = branch.DeepClone() },
                    ["required"] = new JsonArray("value"),
                }, name);
                _generated[variant] = $"[JsonConverter(typeof(ProtocolValueConverter<{variant}, {inner}>))]\n"
                    + $"public sealed class {variant} : {name}, IProtocolValue<{variant}, {inner}>\n"
                    + "{\n"
                    + $"    public {variant}({inner} value) => Value = value;\n\n"
                    + "    [JsonIgnore]\n"
                    + $"    public {inner} Value {{ get; init; }}\n\n"
                    + $"    public static {variant} FromValue({inner} value) => new(value);\n"
                    + "}";
                variants.Add(new ProtocolVariant(variant, inner, true, null));
                if (enumValues is not null)
                    foreach (var value in enumValues)
                        lines.Add($"    public static {name} {Pascal(value)} {{ get; }} = new {variant}({inner}.{Pascal(value)});");
            }
        }
        lines.AddRange([
            "}", "", $"public sealed class {name}JsonConverter : JsonConverter<{name}>", "{",
            $"    public override {name} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)",
            "    {",
        ]);
        if (discriminator is not null)
        {
            lines.Add($"        return ProtocolUnion.ReadDiscriminator(ref reader, {Literal(discriminator)}) switch");
            lines.Add("        {");
            foreach (var variant in variants)
                lines.Add($"            {Literal(variant.Value!)} => JsonSerializer.Deserialize<{variant.Name}>(ref reader, options)!,");
            lines.Add($"            _ => throw new JsonException({Literal("Unknown " + name + " discriminator.")}),");
            lines.Add("        };");
        }
        else
        {
            foreach (var variant in variants)
            {
                var inner = variant.Inner;
                var nullable = inner is not ("long" or "int" or "bool" or "ulong" or "uint" or "ushort" or "double" or "ProtocolNull")
                    && (!_schemas.TryGetValue(inner, out var innerSchema) || EnumValues(innerSchema) is null);
                lines.Add("        {");
                lines.Add("            Utf8JsonReader candidate = reader;");
                lines.Add("            try");
                lines.Add("            {");
                lines.Add($"                {inner} value = JsonSerializer.Deserialize<{inner}>(ref candidate, options)"
                    + (nullable ? " ?? throw new JsonException(\"Expected a non-null union value.\");" : ";\n"));
                lines.Add("                reader = candidate;");
                lines.Add($"                return {(variant.Wrapped ? "new " + variant.Name + "(value)" : "value")};");
                lines.Add("            }");
                lines.Add("            catch (JsonException)");
                lines.Add("            {");
                lines.Add("                // This branch does not match; try the next schema alternative.");
                lines.Add("            }");
                lines.Add("        }");
            }
            lines.Add($"        throw new JsonException({Literal("Value does not match any " + name + " schema alternative.")});");
        }
        lines.AddRange([
            "    }", "", $"    public override void Write(Utf8JsonWriter writer, {name} value, JsonSerializerOptions options)",
            "    {", "        switch (value)", "        {",
        ]);
        foreach (var variant in variants)
        {
            lines.Add($"            case {variant.Name} typed:");
            lines.Add($"                JsonSerializer.Serialize(writer, typed{(variant.Wrapped ? ".Value" : "")}, options);");
            lines.Add("                break;");
        }
        lines.AddRange([
            "            default:", $"                throw new JsonException({Literal("Unknown " + name + " implementation.")});",
            "        }", "    }", "}",
        ]);
        return string.Join('\n', lines);
    }

    private readonly record struct ProtocolVariant(string Name, string Inner, bool Wrapped, string? Value);

    private const string RequestIdBody = """
        [JsonConverter(typeof(RequestIdJsonConverter))]
        public sealed class RequestId : IEquatable<RequestId>
        {
            public RequestId(string value) => String = value ?? throw new ArgumentNullException(nameof(value));
            public RequestId(long value) => Number = value;

            [JsonIgnore]
            public string? String { get; }
            [JsonIgnore]
            public long? Number { get; }

            // Responses carry new instances of the IDs used to key pending requests.
            public bool Equals(RequestId? other) => other is not null && String == other.String && Number == other.Number;
            public override bool Equals(object? obj) => obj is RequestId other && Equals(other);
            public override int GetHashCode() => HashCode.Combine(String, Number);

            public static implicit operator RequestId(string value) => new(value);
            public static implicit operator RequestId(long value) => new(value);
            public override string ToString() => String ?? Number?.ToString(System.Globalization.CultureInfo.InvariantCulture)
                ?? throw new InvalidOperationException("An uninitialized request ID has no wire representation.");
        }

        public sealed class RequestIdJsonConverter : JsonConverter<RequestId>
        {
            public override bool HandleNull => true;

            public override RequestId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
                => reader.TokenType switch
                {
                    JsonTokenType.String => new RequestId(reader.GetString()!),
                    JsonTokenType.Number when reader.TryGetInt64(out long number) => new RequestId(number),
                    _ => throw new JsonException("A request ID must be a string or signed 64-bit integer."),
                };

            public override void Write(Utf8JsonWriter writer, RequestId value, JsonSerializerOptions options)
            {
                if (value is null) throw new JsonException("A request ID must be a string or signed 64-bit integer.");
                if (value.String is { } text) writer.WriteStringValue(text);
                else if (value.Number is { } number) writer.WriteNumberValue(number);
                else throw new JsonException("An uninitialized request ID has no wire representation.");
            }
        }
        """;

    internal Dictionary<string, string> Generate()
    {
        foreach (var name in _named.Order(StringComparer.Ordinal)) Emit(name);
        if (_selection is not null)
        {
            var unused = _selectedTypes.Except(_generated.Keys, StringComparer.Ordinal)
                .Except(_aliases.Keys, StringComparer.Ordinal).Order(StringComparer.Ordinal).ToList();
            if (unused.Count > 0)
                throw new InvalidOperationException("Unused Codex type selection: " + string.Join(", ", unused));
        }
        var files = _generated.OrderBy(pair => pair.Key, StringComparer.Ordinal)
            .ToDictionary(pair => pair.Key + ".g.cs", pair => Header + pair.Value + "\n", StringComparer.Ordinal);
        var manifest = new JsonObject
        {
            ["schemaSha256"] = _sourceHash,
            ["selectionSha256"] = _selectionHash,
            ["schemaFiles"] = _schemaFiles,
            ["namedDefinitions"] = _allNamed.Count,
            ["selectedRoots"] = new JsonArray(_named.Order(StringComparer.Ordinal)
                .Select(name => (JsonNode?)JsonValue.Create(name)).ToArray()),
            ["generatedTypes"] = _generated.Count,
            ["primitiveAliases"] = new JsonObject(_aliases.OrderBy(pair => pair.Key, StringComparer.Ordinal)
                .Select(pair => KeyValuePair.Create<string, JsonNode?>(pair.Key, JsonValue.Create(pair.Value)))),
        };
        files["manifest.json"] = manifest.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + "\n";
        return files;
    }
}

internal static class ProtocolGeneratorTests
{
    internal static void Run()
    {
        foreach (var (first, second, expected) in new[]
        {
            ("JSONRPCResponse", "JSONRPCMessage", "JSONRPCResponseMessage"),
            ("McpBooleanSchema", "McpPrimitiveSchema", "McpBooleanPrimitiveSchema"),
            ("Version2Event", "Version2Notice", "Version2EventNotice"),
            ("Foo", "Food", "FooFood"),
        })
            Check(ProtocolGenerator.CombineTypeNames(first, second) == expected, "shared name words");
        Check(ProtocolGenerator.NestedTypeName("GranularAskForApproval", "Granular", JsonNode.Parse("{\"type\":\"object\"}"))
            == "GranularAskForApprovalGranular", "nested owner context");
        Check(ProtocolGenerator.VariantTypeName("Result", "Result") == "ResultVariant", "variant base collision");
        Check(ProtocolGenerator.VariantTypeName("McpElicitationUntitledSingleSelectEnumSchema", "McpElicitationSingleSelectEnumSchema", true)
            == "McpElicitationUntitledSingleSelectEnumSchemaVariant", "wrapped variant collision");

        var selectionDefinitions = """
            {"Reply":{"type":"object","properties":{"value":{"$ref":"#/definitions/Choice"},"unused":{"type":"string"}},"required":["value","unused"]},
             "Choice":{"oneOf":[
               {"title":"FirstChoice","type":"object","properties":{"type":{"type":"string","enum":["first"]},"answer":{"type":"string"},"extra":{"type":"string"}},"required":["type","answer","extra"]},
               {"title":"SecondChoice","type":"object","properties":{"type":{"type":"string","enum":["second"]}},"required":["type"]}]},
             "Unrelated":{"type":"object","properties":{"x":{"type":"string"}}}}
            """;
        var selected = Generate(selectionDefinitions, """
            {"roots":["Reply"],"types":{"Reply":["value"],"Choice":{"variants":{"first":["answer"]}}}}
            """);
        Check(selected.Keys.ToHashSet(StringComparer.Ordinal).SetEquals(["Reply.g.cs", "Choice.g.cs", "FirstChoice.g.cs", "manifest.json"]),
            "selected output closure");
        Check(selected["Reply.g.cs"].Contains("[JsonPropertyName(\"value\")]", StringComparison.Ordinal)
            && !selected["Reply.g.cs"].Contains("Unused", StringComparison.Ordinal)
            && !selected["FirstChoice.g.cs"].Contains("Extra", StringComparison.Ordinal)
            && !selected["Choice.g.cs"].Contains("SecondChoice", StringComparison.Ordinal), "selected fields and variants");
        var referenceDefinitions = """
            {"Reply":{"type":"object","properties":{"child":{"$ref":"#/definitions/Child"}}},
             "Child":{"type":"object","properties":{"text":{"type":"string"}}}}
            """;
        ExpectFailure(() => Generate(referenceDefinitions, """{"roots":["Reply"],"types":{"Reply":["missing"]}}"""),
            "Unknown selected field");
        ExpectFailure(() => Generate(referenceDefinitions, """{"roots":["Reply"],"types":{"Reply":["child"]}}"""),
            "lacks a selection: Child");
        ExpectFailure(() => Generate("""
            {"Reply":{"type":"object","additionalProperties":false,"properties":{"kept":{"type":"string"},"dropped":{"type":"string"}}}}
            """, """{"roots":["Reply"],"types":{"Reply":["kept"]}}"""),
            "Closed Codex object needs all fields");

        var collisionDefinitions = """
            {"AcceptWithPolicyDetails":{"type":"object","properties":{"original":{"type":"boolean"}}},
             "FirstAcceptWithPolicyDecision":{"type":"object","properties":{"acceptWithPolicy":{"type":"object","properties":{"value":{"type":"string"}}}}},
             "SecondAcceptWithPolicyDecision":{"type":"object","properties":{"acceptWithPolicy":{"type":"object","properties":{"value":{"type":"integer"}}}}}}
            """;
        var collisions = Generate(collisionDefinitions);
        Check(collisions["FirstAcceptWithPolicyDecision.g.cs"].Contains("AcceptWithPolicyDetails2? AcceptWithPolicy", StringComparison.Ordinal)
            && collisions["SecondAcceptWithPolicyDecision.g.cs"].Contains("AcceptWithPolicyDetails3? AcceptWithPolicy", StringComparison.Ordinal),
            "anonymous type collisions");
        var variants = Generate("""
            {"FirstResult":{"oneOf":[{"title":"SharedVariant","type":"object","properties":{"value":{"type":"string"}},"required":["value"]}]},
             "SecondResult":{"oneOf":[{"title":"SharedVariant","type":"object","properties":{"value":{"type":"string"}},"required":["value"]}]}}
            """);
        Check(variants["SharedVariant.g.cs"].Contains("class SharedVariant : FirstResult", StringComparison.Ordinal)
            && variants["SharedVariant2.g.cs"].Contains("class SharedVariant2 : SecondResult", StringComparison.Ordinal),
            "variants retain their base class");
    }

    private static Dictionary<string, string> Generate(string definitions, string? selection = null)
    {
        var directory = Path.Combine(Path.GetTempPath(), "goblin-protocol-generator-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(directory);
        try
        {
            File.WriteAllText(Path.Combine(directory, "codex_app_server_protocol.schemas.json"),
                "{\"definitions\":" + definitions + "}");
            return new ProtocolGenerator(directory, selection).Generate();
        }
        finally { Directory.Delete(directory, true); }
    }

    private static void Check(bool condition, string message)
    {
        if (!condition) throw new InvalidOperationException("Generator test failed: " + message);
    }

    private static void ExpectFailure(Action action, string message)
    {
        try { action(); }
        catch (InvalidOperationException error) when (error.Message.Contains(message, StringComparison.Ordinal)) { return; }
        throw new InvalidOperationException("Generator test failed: expected " + message);
    }
}
