<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Goblin.Core/Goblin.Core.csproj" />
    <ProjectReference Include="../Goblin.Contracts/Goblin.Contracts.csproj" />
    <ProjectReference Include="../Goblin.Persistence/Goblin.Persistence.csproj" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="6.39.1" />
    <PackageReference Include="WolverineFx.Postgresql" Version="6.39.1" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.39.1" />
  </ItemGroup>
</Project>
