// Generated by scripts/generate-contract-values.mts. Edit the owning C#/Rust declaration.
export const WorkStatus = {
    Ready: "Ready",
    Queued: "Queued",
    InProgress: "InProgress",
    Cancelling: "Cancelling",
    NeedsAttention: "NeedsAttention",
    Completed: "Completed",
    Cancelled: "Cancelled",
} as const;
export type WorkStatus = (typeof WorkStatus)[keyof typeof WorkStatus];

export const AttemptStatus = {
    Queued: "Queued",
    Starting: "Starting",
    Running: "Running",
    CancellationRequested: "CancellationRequested",
    Succeeded: "Succeeded",
    Failed: "Failed",
    Uncertain: "Uncertain",
    Cancelled: "Cancelled",
    Waiting: "Waiting",
} as const;
export type AttemptStatus = (typeof AttemptStatus)[keyof typeof AttemptStatus];

export const AttentionReason = {
    InputRequired: "InputRequired",
    ResultReview: "ResultReview",
    Failure: "Failure",
    UncertainExecution: "UncertainExecution",
    CleanupRequired: "CleanupRequired",
    RepositoryRequired: "RepositoryRequired",
} as const;
export type AttentionReason =
    (typeof AttentionReason)[keyof typeof AttentionReason];

export const FailureKind = {
    DispatchFailed: "DispatchFailed",
    ConnectionUnavailable: "ConnectionUnavailable",
    CapabilityUnavailable: "CapabilityUnavailable",
    HostUnavailable: "HostUnavailable",
    ExecutionFailed: "ExecutionFailed",
    TimedOut: "TimedOut",
    RuntimeDisconnected: "RuntimeDisconnected",
    CancellationFailed: "CancellationFailed",
    CleanupFailed: "CleanupFailed",
    StorageUnavailable: "StorageUnavailable",
} as const;
export type FailureKind = (typeof FailureKind)[keyof typeof FailureKind];

export const WorkEventKind = {
    Created: "Created",
    Assigned: "Assigned",
    ExecutionQueued: "ExecutionQueued",
    ExecutionClaimed: "ExecutionClaimed",
    ExecutionStarted: "ExecutionStarted",
    ExecutionFailed: "ExecutionFailed",
    ExecutionUncertain: "ExecutionUncertain",
    ExecutionStopped: "ExecutionStopped",
    RetryRequested: "RetryRequested",
    InputRequested: "InputRequested",
    InputProvided: "InputProvided",
    ResultProposed: "ResultProposed",
    ChangesRequested: "ChangesRequested",
    ResultApproved: "ResultApproved",
    CancellationRequested: "CancellationRequested",
    Cancelled: "Cancelled",
    ContextAdded: "ContextAdded",
    ProgressReported: "ProgressReported",
    ArtifactRecorded: "ArtifactRecorded",
    CleanupRequired: "CleanupRequired",
    CleanupFailed: "CleanupFailed",
    CleanupCompleted: "CleanupCompleted",
    ExecutionContinued: "ExecutionContinued",
    WorkspaceSaved: "WorkspaceSaved",
    WorkspaceReleased: "WorkspaceReleased",
    RepositoryRequested: "RepositoryRequested",
    RepositoryAuthorized: "RepositoryAuthorized",
    RepositoryDenied: "RepositoryDenied",
    RepositoryAuthorizationInvalidated: "RepositoryAuthorizationInvalidated",
} as const;
export type WorkEventKind = (typeof WorkEventKind)[keyof typeof WorkEventKind];

export const RepositoryAuthorizationStatus = {
    Pending: "Pending",
    Authorized: "Authorized",
    Denied: "Denied",
    Invalidated: "Invalidated",
} as const;
export type RepositoryAuthorizationStatus =
    (typeof RepositoryAuthorizationStatus)[keyof typeof RepositoryAuthorizationStatus];

export const InspectionState = {
    Queued: "Queued",
    Starting: "Starting",
    Available: "Available",
    Stopping: "Stopping",
    Stopped: "Stopped",
    NeedsAttention: "NeedsAttention",
} as const;
export type InspectionState =
    (typeof InspectionState)[keyof typeof InspectionState];

export const InspectionObservation = {
    Pending: "Pending",
    Running: "Running",
    Missing: "Missing",
    Failed: "Failed",
} as const;
export type InspectionObservation =
    (typeof InspectionObservation)[keyof typeof InspectionObservation];

export const WorkAction = {
    Create: "Create",
    Assign: "Assign",
    Execute: "Execute",
    Retry: "Retry",
    Cancel: "Cancel",
    Answer: "Answer",
    RequestChanges: "RequestChanges",
    Approve: "Approve",
    AddContext: "AddContext",
    Reconcile: "Reconcile",
    PrepareRepository: "PrepareRepository",
    AuthorizeRepository: "AuthorizeRepository",
    DenyRepository: "DenyRepository",
} as const;
export type WorkAction = (typeof WorkAction)[keyof typeof WorkAction];

export const IdentityKind = {
    Work: "Work",
    Command: "Command",
    Conversation: "Conversation",
    Message: "Message",
    Attempt: "Attempt",
    Event: "Event",
    Inspection: "Inspection",
    RepositoryOperation: "RepositoryOperation",
} as const;
export type IdentityKind = (typeof IdentityKind)[keyof typeof IdentityKind];

export const NoticeKind = { Error: "error", Info: "info" } as const;
export type NoticeKind = (typeof NoticeKind)[keyof typeof NoticeKind];

export const VerificationState = {
    Accepted: "accepted",
    Unverified: "unverified",
} as const;
export type VerificationState =
    (typeof VerificationState)[keyof typeof VerificationState];

export const AuthenticationMethod = {
    ApiKey: "apiKey",
    ChatGPT: "chatgpt",
} as const;
export type AuthenticationMethod =
    (typeof AuthenticationMethod)[keyof typeof AuthenticationMethod];

export const GitHubConnectionStatus = {
    Disconnected: "Disconnected",
    Connecting: "Connecting",
    Connected: "Connected",
    Unavailable: "Unavailable",
} as const;
export type GitHubConnectionStatus =
    (typeof GitHubConnectionStatus)[keyof typeof GitHubConnectionStatus];

export const ConnectionAvailability = {
    Disconnected: "Disconnected",
    Available: "Available",
    Unavailable: "Unavailable",
    Changing: "Changing",
    Verifying: "Verifying",
} as const;
export type ConnectionAvailability =
    (typeof ConnectionAvailability)[keyof typeof ConnectionAvailability];

export const RepositoryOperationState = {
    Queued: "Queued",
    Running: "Running",
    Succeeded: "Succeeded",
    Failed: "Failed",
    Uncertain: "Uncertain",
} as const;
export type RepositoryOperationState =
    (typeof RepositoryOperationState)[keyof typeof RepositoryOperationState];

export function isContractValue<T extends Record<string, string>>(
    values: T,
    value: unknown,
): value is T[keyof T] {
    return typeof value === "string" && Object.values(values).includes(value);
}
