// Generated by scripts/generate-contract-values.mts. Edit the owning C#/Rust declaration.
export const SetupAction = Object.freeze({
  Init: "init",
  Begin: "begin",
  Start: "start",
  Detail: "detail",
  PublicUrl: "public-url",
  Complete: "complete",
  FailStep: "fail-step",
  Handoff: "handoff",
  Failed: "failed",
  Ready: "ready",
});

export const SetupStatus = Object.freeze({
  Waiting: "waiting",
  Running: "running",
  Failed: "failed",
  Ready: "ready",
});

export const SetupPhase = Object.freeze({
  Installing: "installing",
  Activating: "activating",
  Complete: "complete",
});

export const SetupStepStatus = Object.freeze({
  Waiting: "waiting",
  Running: "running",
  Complete: "complete",
  Failed: "failed",
});

export const SetupStep = Object.freeze({
  Prepare: "prepare",
  K3s: "k3s",
  CertManager: "cert-manager",
  Sandbox: "sandbox",
  Image: "image",
  Prefetch: "prefetch",
  Database: "database",
  Import: "import",
  Migrate: "migrate",
  Deploy: "deploy",
  Verify: "verify",
  Activate: "activate",
});

export function isSetupState(state) {
  return (
    state?.version === 1 &&
    Object.values(SetupStatus).includes(state.status) &&
    Object.values(SetupPhase).includes(state.phase) &&
    Array.isArray(state.steps) &&
    state.steps.every(
      (step) =>
        Object.values(SetupStep).includes(step.id) &&
        Object.values(SetupStepStatus).includes(step.status),
    )
  );
}
