import { test, expect } from "@playwright/test";
import { writeFile, unlink } from "node:fs/promises";
import { resolve } from "node:path";

test("owner can use a one-character deployment password, connect ChatGPT, and switch to an API key", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Open your workspace" })).toBeVisible();
  await expect(page.getByLabel("Goblin password", { exact: true })).toHaveAttribute("autocomplete", "current-password");
  await page.getByLabel("Goblin password", { exact: true }).fill("incorrect-password");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await expect(page.getByRole("alert")).toContainText("The Goblin password is incorrect.");
  await expect(page.getByLabel("Goblin password", { exact: true })).toHaveValue("");
  await page.getByLabel("Goblin password", { exact: true }).fill("a");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await expect(page.getByRole("heading", { name: "Choose how to sign in" })).toBeVisible();
  await page.screenshot({ path: "test-results/authentication-connect.png", fullPage: true });

  await page.getByRole("button", { name: "Continue with ChatGPT" }).click();
  await expect(page.getByText("ABCD-1234", { exact: true })).toBeVisible();
  await expect(page.getByRole("link", { name: "Open OpenAI sign-in" })).toHaveAttribute("href", "https://auth.openai.com/codex/device");
  await page.reload();
  await expect(page.getByText("ABCD-1234", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Cancel sign-in" }).click();
  await expect(page.getByRole("heading", { name: "Choose how to sign in" })).toBeVisible();

  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Continue with ChatGPT" }).click();
  await expect(page.getByText("ABCD-1234", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/authentication-device-mobile.png", fullPage: true });
  const completion = resolve(".goblin-browser-test/codex/complete-login");
  await writeFile(completion, "complete");
  await expect(page.getByText("owner@example.test · plus", { exact: true })).toBeVisible({ timeout: 8000 });
  await unlink(completion);
  await page.getByLabel("Try a simple prompt").fill("Say hello in one sentence.");
  await page.getByRole("button", { name: "Send test prompt" }).click();
  await expect(page.locator("#prompt-reply")).toHaveText("Hello from the connected account.");
  await expect(page.locator("#prompt-details")).toContainText("ChatGPT · test-model");
  await page.screenshot({ path: "test-results/prompt-test-mobile.png", fullPage: true });
  await page.getByLabel("Try a simple prompt").fill("Trigger a simulated failure.");
  await page.getByRole("button", { name: "Send test prompt" }).click();
  await expect(page.getByRole("alert")).toContainText("OpenAI rejected the saved login");
  await expect(page.locator("#prompt-result")).toBeHidden();
  await expect(page.locator("#prompt-reply")).toHaveText("");
  await expect(page.locator("body")).not.toContainText("THIS-MUST-NOT-LEAK");
  await page.getByRole("button", { name: "Lock preview" }).click();
  await expect(page.getByRole("heading", { name: "Open your workspace" })).toBeVisible();
  await page.getByLabel("Goblin password", { exact: true }).fill("a");
  await page.getByRole("button", { name: "Open workspace" }).click();
  await expect(page.getByText("owner@example.test · plus", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Disconnect Codex" }).click();
  await expect(page.getByRole("heading", { name: "Choose how to sign in" })).toBeVisible();

  await page.getByText("Use an OpenAI API key instead", { exact: false }).click();
  await page.getByLabel("OpenAI API key", { exact: true }).fill("sk-invalid-fake-browser-test-key");
  await page.getByRole("button", { name: "Connect API key" }).click();
  await expect(page.getByRole("alert")).toContainText("OpenAI rejected this API key");
  await expect(page.getByLabel("OpenAI API key", { exact: true })).toHaveValue("");
  await page.getByLabel("OpenAI API key", { exact: true }).fill("sk-valid-fake-browser-test-key");
  await page.getByRole("button", { name: "Connect API key" }).click();
  await expect(page.getByText("Billed to your OpenAI Platform project", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Send test prompt" }).click();
  await expect(page.locator("#prompt-details")).toContainText("OpenAI API key · test-model");
  expect(await page.evaluate(() => ({ local: localStorage.length, session: sessionStorage.length }))).toEqual({ local: 0, session: 0 });
  await expect(page.locator("body")).not.toContainText("sk-valid-fake-browser-test-key");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
