// Generate browser values from their owning C#/Rust declarations, never a second value list.
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";

type Values = Record<string, Record<string, string>>;
const sources: Record<string, string[]> = {
    "backend/src/Goblin.Contracts/Conversations/ExternalConversations.cs": [
        "SlackConnectionStatus",
        "SlackSetupStatus",
    ],
    "backend/src/Goblin.Core/Work/WorkTypes.cs": [
        "WorkStatus",
        "AttemptStatus",
        "AttentionReason",
        "FailureKind",
        "WorkEventKind",
    ],
    "backend/src/Goblin.Core/Work/GitRepositoryAuthorization.cs": [
        "GitRepositoryAuthorizationStatus",
    ],
    "backend/src/Goblin.Core/Work/WorkspaceSessionRules.cs": [
        "InspectionState",
        "InspectionObservation",
    ],
    "backend/src/Goblin.Application/Work/WorkContracts.cs": ["WorkAction"],
    "backend/src/Goblin.Application/Work/IdentityStore.cs": ["IdentityKind"],
    "backend/src/Goblin.Contracts/ContractValues.cs": [
        "NoticeKind",
        "VerificationState",
        "AuthenticationMethod",
        "GitHubConnectionStatus",
        "ConnectionAvailability",
        "GitRepositoryOperationState",
    ],
};

function add(values: Record<string, string>, name: string, wire: string) {
    if (Object.hasOwn(values, name) || Object.values(values).includes(wire))
        throw new Error(`Duplicate contract member: ${name}/${wire}`);
    values[name] = wire;
}

// Deliberately support only simple string enums. Fail closed if a declaration evolves.
export function csharpValues(source: string, names: string[]): Values {
    const result: Values = {};
    for (const name of names) {
        const body = source.match(
            new RegExp(`public enum ${name}\\s*\\{([^}]+)\\}`),
        )?.[1];
        if (!body) throw new Error(`Missing contract enum: ${name}`);
        const values: Record<string, string> = {};
        for (const entry of body
            .replace(/\/\/[^\n]*/g, "")
            .split(",")
            .map((s) => s.trim())
            .filter(Boolean)) {
            const member = entry.match(
                /^(?:\[JsonStringEnumMemberName\("([^"\\]+)"\)\]\s*)?([A-Za-z][A-Za-z0-9]*)$/,
            );
            if (!member)
                throw new Error(
                    `Unsupported contract declaration: ${name}.${entry}`,
                );
            add(values, member[2]!, member[1] ?? member[2]!);
        }
        result[name] = values;
    }
    return result;
}

export function rustValues(source: string): Values {
    const result: Values = {};
    for (const match of source.matchAll(
        /contract_values!\((\w+)\s*\{([^}]+)\}\);/g,
    )) {
        const values: Record<string, string> = {};
        for (const entry of match[2]!
            .split(",")
            .map((s) => s.trim())
            .filter(Boolean)) {
            const member = entry.match(/^(\w+)\s*=>\s*"([^"\\]+)"$/);
            if (!member) throw new Error(`Unsupported Rust contract: ${entry}`);
            add(values, member[1]!, member[2]!);
        }
        if (Object.hasOwn(result, match[1]!))
            throw new Error(`Duplicate contract: ${match[1]}`);
        result[match[1]!] = values;
    }
    if (!Object.keys(result).length) throw new Error("Missing Rust contracts");
    return result;
}

export async function generate(root: string, check: boolean) {
    const contracts: Values = {};
    for (const [path, names] of Object.entries(sources)) {
        const values = csharpValues(
            await readFile(resolve(root, path), "utf8"),
            names,
        );
        // GitRepositoryEnumJsonConverter preserves earlier JSON spellings at the
        // C# adapter boundary. Apply that policy to values, never identifiers.
        for (const [name, members] of Object.entries(values))
            contracts[name] = Object.fromEntries(
                Object.entries(members).map(([member, wire]) => [
                    member,
                    wire.replaceAll("GitRepository", "Repository"),
                ]),
            );
    }
    const setup = rustValues(
        await readFile(
            resolve(root, "tools/goblinctl/src/contract_values.rs"),
            "utf8",
        ),
    );
    const header =
        "// Generated by scripts/generate-contract-values.mts. Edit the owning C#/Rust declaration.\n";
    const ts =
        header +
        Object.entries(contracts)
            .map(
                ([name, values]) =>
                    `export const ${name} = ${JSON.stringify(values)} as const;\nexport type ${name} = (typeof ${name})[keyof typeof ${name}];\n`,
            )
            .join("\n") +
        `
export function isContractValue<T extends Record<string, string>>(values: T, value: unknown): value is T[keyof T] {
    return typeof value === "string" && Object.values(values).includes(value);
}
`;
    const js =
        header +
        Object.entries(setup)
            .map(
                ([name, values]) =>
                    `export const ${name} = Object.freeze(${JSON.stringify(values)});\n`,
            )
            .join("\n") +
        `
export function isSetupState(state) {
    return state?.version === 1 && Object.values(SetupStatus).includes(state.status) &&
        Object.values(SetupPhase).includes(state.phase) && Array.isArray(state.steps) &&
        state.steps.every(step => Object.values(SetupStep).includes(step.id) && Object.values(SetupStepStatus).includes(step.status));
}
`;
    for (const [path, data] of [
        [
            "frontend/src/api/values.ts",
            await format(ts, { parser: "typescript", tabWidth: 4 }),
        ],
        [
            "deploy/azure/setup/contract-values.js",
            await format(js, { parser: "babel", tabWidth: 2 }),
        ],
    ]) {
        const output = resolve(root, path!);
        if (check) {
            if ((await readFile(output, "utf8")) !== data)
                throw new Error(
                    `Stale generated contracts: ${path}. Run make contracts-generate.`,
                );
        } else await writeFile(output, data!);
    }
}

if (
    process.argv[1] &&
    fileURLToPath(import.meta.url) === resolve(process.argv[1])
) {
    const args = process.argv.slice(2);
    if (args.some((arg) => arg !== "--check"))
        throw new Error("Usage: generate-contract-values.mts [--check]");
    await generate(
        fileURLToPath(new URL("../", import.meta.url)),
        args.includes("--check"),
    );
}
