// Generated from the public-domain IANA tzdb 2026c: zone.tab and tzdata.zi.
// https://data.iana.org/time-zones/releases/tzdata2026c.tar.gz
// Regenerate with: node scripts/update-timezone-places.mts /usr/share/zoneinfo
// zone.tab preserves a country and city for each selectable geographic zone.
export const timeZonePlaces: Readonly<
    Record<string, readonly [country: string, city: string]>
> = {
    "Africa/Abidjan": ["CI", "Abidjan"],
    "Africa/Accra": ["GH", "Accra"],
    "Africa/Addis_Ababa": ["ET", "Addis Ababa"],
    "Africa/Algiers": ["DZ", "Algiers"],
    "Africa/Asmara": ["ER", "Asmara"],
    "Africa/Asmera": ["ER", "Asmara"],
    "Africa/Bamako": ["ML", "Bamako"],
    "Africa/Bangui": ["CF", "Bangui"],
    "Africa/Banjul": ["GM", "Banjul"],
    "Africa/Bissau": ["GW", "Bissau"],
    "Africa/Blantyre": ["MW", "Blantyre"],
    "Africa/Brazzaville": ["CG", "Brazzaville"],
    "Africa/Bujumbura": ["BI", "Bujumbura"],
    "Africa/Cairo": ["EG", "Cairo"],
    "Africa/Casablanca": ["MA", "Casablanca"],
    "Africa/Ceuta": ["ES", "Ceuta"],
    "Africa/Conakry": ["GN", "Conakry"],
    "Africa/Dakar": ["SN", "Dakar"],
    "Africa/Dar_es_Salaam": ["TZ", "Dar es Salaam"],
    "Africa/Djibouti": ["DJ", "Djibouti"],
    "Africa/Douala": ["CM", "Douala"],
    "Africa/El_Aaiun": ["EH", "El Aaiun"],
    "Africa/Freetown": ["SL", "Freetown"],
    "Africa/Gaborone": ["BW", "Gaborone"],
    "Africa/Harare": ["ZW", "Harare"],
    "Africa/Johannesburg": ["ZA", "Johannesburg"],
    "Africa/Juba": ["SS", "Juba"],
    "Africa/Kampala": ["UG", "Kampala"],
    "Africa/Khartoum": ["SD", "Khartoum"],
    "Africa/Kigali": ["RW", "Kigali"],
    "Africa/Kinshasa": ["CD", "Kinshasa"],
    "Africa/Lagos": ["NG", "Lagos"],
    "Africa/Libreville": ["GA", "Libreville"],
    "Africa/Lome": ["TG", "Lome"],
    "Africa/Luanda": ["AO", "Luanda"],
    "Africa/Lubumbashi": ["CD", "Lubumbashi"],
    "Africa/Lusaka": ["ZM", "Lusaka"],
    "Africa/Malabo": ["GQ", "Malabo"],
    "Africa/Maputo": ["MZ", "Maputo"],
    "Africa/Maseru": ["LS", "Maseru"],
    "Africa/Mbabane": ["SZ", "Mbabane"],
    "Africa/Mogadishu": ["SO", "Mogadishu"],
    "Africa/Monrovia": ["LR", "Monrovia"],
    "Africa/Nairobi": ["KE", "Nairobi"],
    "Africa/Ndjamena": ["TD", "Ndjamena"],
    "Africa/Niamey": ["NE", "Niamey"],
    "Africa/Nouakchott": ["MR", "Nouakchott"],
    "Africa/Ouagadougou": ["BF", "Ouagadougou"],
    "Africa/Porto-Novo": ["BJ", "Porto-Novo"],
    "Africa/Sao_Tome": ["ST", "Sao Tome"],
    "Africa/Timbuktu": ["ML", "Bamako"],
    "Africa/Tripoli": ["LY", "Tripoli"],
    "Africa/Tunis": ["TN", "Tunis"],
    "Africa/Windhoek": ["NA", "Windhoek"],
    "America/Adak": ["US", "Adak"],
    "America/Anchorage": ["US", "Anchorage"],
    "America/Anguilla": ["AI", "Anguilla"],
    "America/Antigua": ["AG", "Antigua"],
    "America/Araguaina": ["BR", "Araguaina"],
    "America/Argentina/Buenos_Aires": ["AR", "Argentina / Buenos Aires"],
    "America/Argentina/Catamarca": ["AR", "Argentina / Catamarca"],
    "America/Argentina/ComodRivadavia": ["AR", "Argentina / Catamarca"],
    "America/Argentina/Cordoba": ["AR", "Argentina / Cordoba"],
    "America/Argentina/Jujuy": ["AR", "Argentina / Jujuy"],
    "America/Argentina/La_Rioja": ["AR", "Argentina / La Rioja"],
    "America/Argentina/Mendoza": ["AR", "Argentina / Mendoza"],
    "America/Argentina/Rio_Gallegos": ["AR", "Argentina / Rio Gallegos"],
    "America/Argentina/Salta": ["AR", "Argentina / Salta"],
    "America/Argentina/San_Juan": ["AR", "Argentina / San Juan"],
    "America/Argentina/San_Luis": ["AR", "Argentina / San Luis"],
    "America/Argentina/Tucuman": ["AR", "Argentina / Tucuman"],
    "America/Argentina/Ushuaia": ["AR", "Argentina / Ushuaia"],
    "America/Aruba": ["AW", "Aruba"],
    "America/Asuncion": ["PY", "Asuncion"],
    "America/Atikokan": ["CA", "Atikokan"],
    "America/Atka": ["US", "Adak"],
    "America/Bahia": ["BR", "Bahia"],
    "America/Bahia_Banderas": ["MX", "Bahia Banderas"],
    "America/Barbados": ["BB", "Barbados"],
    "America/Belem": ["BR", "Belem"],
    "America/Belize": ["BZ", "Belize"],
    "America/Blanc-Sablon": ["CA", "Blanc-Sablon"],
    "America/Boa_Vista": ["BR", "Boa Vista"],
    "America/Bogota": ["CO", "Bogota"],
    "America/Boise": ["US", "Boise"],
    "America/Buenos_Aires": ["AR", "Argentina / Buenos Aires"],
    "America/Cambridge_Bay": ["CA", "Cambridge Bay"],
    "America/Campo_Grande": ["BR", "Campo Grande"],
    "America/Cancun": ["MX", "Cancun"],
    "America/Caracas": ["VE", "Caracas"],
    "America/Catamarca": ["AR", "Argentina / Catamarca"],
    "America/Cayenne": ["GF", "Cayenne"],
    "America/Cayman": ["KY", "Cayman"],
    "America/Chicago": ["US", "Chicago"],
    "America/Chihuahua": ["MX", "Chihuahua"],
    "America/Ciudad_Juarez": ["MX", "Ciudad Juarez"],
    "America/Coral_Harbour": ["CA", "Atikokan"],
    "America/Cordoba": ["AR", "Argentina / Cordoba"],
    "America/Costa_Rica": ["CR", "Costa Rica"],
    "America/Coyhaique": ["CL", "Coyhaique"],
    "America/Creston": ["CA", "Creston"],
    "America/Cuiaba": ["BR", "Cuiaba"],
    "America/Curacao": ["CW", "Curacao"],
    "America/Danmarkshavn": ["GL", "Danmarkshavn"],
    "America/Dawson": ["CA", "Dawson"],
    "America/Dawson_Creek": ["CA", "Dawson Creek"],
    "America/Denver": ["US", "Denver"],
    "America/Detroit": ["US", "Detroit"],
    "America/Dominica": ["DM", "Dominica"],
    "America/Edmonton": ["CA", "Edmonton"],
    "America/Eirunepe": ["BR", "Eirunepe"],
    "America/El_Salvador": ["SV", "El Salvador"],
    "America/Ensenada": ["MX", "Tijuana"],
    "America/Fort_Nelson": ["CA", "Fort Nelson"],
    "America/Fort_Wayne": ["US", "Indiana / Indianapolis"],
    "America/Fortaleza": ["BR", "Fortaleza"],
    "America/Glace_Bay": ["CA", "Glace Bay"],
    "America/Godthab": ["GL", "Nuuk"],
    "America/Goose_Bay": ["CA", "Goose Bay"],
    "America/Grand_Turk": ["TC", "Grand Turk"],
    "America/Grenada": ["GD", "Grenada"],
    "America/Guadeloupe": ["GP", "Guadeloupe"],
    "America/Guatemala": ["GT", "Guatemala"],
    "America/Guayaquil": ["EC", "Guayaquil"],
    "America/Guyana": ["GY", "Guyana"],
    "America/Halifax": ["CA", "Halifax"],
    "America/Havana": ["CU", "Havana"],
    "America/Hermosillo": ["MX", "Hermosillo"],
    "America/Indiana/Indianapolis": ["US", "Indiana / Indianapolis"],
    "America/Indiana/Knox": ["US", "Indiana / Knox"],
    "America/Indiana/Marengo": ["US", "Indiana / Marengo"],
    "America/Indiana/Petersburg": ["US", "Indiana / Petersburg"],
    "America/Indiana/Tell_City": ["US", "Indiana / Tell City"],
    "America/Indiana/Vevay": ["US", "Indiana / Vevay"],
    "America/Indiana/Vincennes": ["US", "Indiana / Vincennes"],
    "America/Indiana/Winamac": ["US", "Indiana / Winamac"],
    "America/Indianapolis": ["US", "Indiana / Indianapolis"],
    "America/Inuvik": ["CA", "Inuvik"],
    "America/Iqaluit": ["CA", "Iqaluit"],
    "America/Jamaica": ["JM", "Jamaica"],
    "America/Jujuy": ["AR", "Argentina / Jujuy"],
    "America/Juneau": ["US", "Juneau"],
    "America/Kentucky/Louisville": ["US", "Kentucky / Louisville"],
    "America/Kentucky/Monticello": ["US", "Kentucky / Monticello"],
    "America/Knox_IN": ["US", "Indiana / Knox"],
    "America/Kralendijk": ["BQ", "Kralendijk"],
    "America/La_Paz": ["BO", "La Paz"],
    "America/Lima": ["PE", "Lima"],
    "America/Los_Angeles": ["US", "Los Angeles"],
    "America/Louisville": ["US", "Kentucky / Louisville"],
    "America/Lower_Princes": ["SX", "Lower Princes"],
    "America/Maceio": ["BR", "Maceio"],
    "America/Managua": ["NI", "Managua"],
    "America/Manaus": ["BR", "Manaus"],
    "America/Marigot": ["MF", "Marigot"],
    "America/Martinique": ["MQ", "Martinique"],
    "America/Matamoros": ["MX", "Matamoros"],
    "America/Mazatlan": ["MX", "Mazatlan"],
    "America/Mendoza": ["AR", "Argentina / Mendoza"],
    "America/Menominee": ["US", "Menominee"],
    "America/Merida": ["MX", "Merida"],
    "America/Metlakatla": ["US", "Metlakatla"],
    "America/Mexico_City": ["MX", "Mexico City"],
    "America/Miquelon": ["PM", "Miquelon"],
    "America/Moncton": ["CA", "Moncton"],
    "America/Monterrey": ["MX", "Monterrey"],
    "America/Montevideo": ["UY", "Montevideo"],
    "America/Montreal": ["CA", "Toronto"],
    "America/Montserrat": ["MS", "Montserrat"],
    "America/Nassau": ["BS", "Nassau"],
    "America/New_York": ["US", "New York"],
    "America/Nipigon": ["CA", "Toronto"],
    "America/Nome": ["US", "Nome"],
    "America/Noronha": ["BR", "Noronha"],
    "America/North_Dakota/Beulah": ["US", "North Dakota / Beulah"],
    "America/North_Dakota/Center": ["US", "North Dakota / Center"],
    "America/North_Dakota/New_Salem": ["US", "North Dakota / New Salem"],
    "America/Nuuk": ["GL", "Nuuk"],
    "America/Ojinaga": ["MX", "Ojinaga"],
    "America/Panama": ["PA", "Panama"],
    "America/Pangnirtung": ["CA", "Iqaluit"],
    "America/Paramaribo": ["SR", "Paramaribo"],
    "America/Phoenix": ["US", "Phoenix"],
    "America/Port_of_Spain": ["TT", "Port of Spain"],
    "America/Port-au-Prince": ["HT", "Port-au-Prince"],
    "America/Porto_Acre": ["BR", "Rio Branco"],
    "America/Porto_Velho": ["BR", "Porto Velho"],
    "America/Puerto_Rico": ["PR", "Puerto Rico"],
    "America/Punta_Arenas": ["CL", "Punta Arenas"],
    "America/Rainy_River": ["CA", "Winnipeg"],
    "America/Rankin_Inlet": ["CA", "Rankin Inlet"],
    "America/Recife": ["BR", "Recife"],
    "America/Regina": ["CA", "Regina"],
    "America/Resolute": ["CA", "Resolute"],
    "America/Rio_Branco": ["BR", "Rio Branco"],
    "America/Rosario": ["AR", "Argentina / Cordoba"],
    "America/Santa_Isabel": ["MX", "Tijuana"],
    "America/Santarem": ["BR", "Santarem"],
    "America/Santiago": ["CL", "Santiago"],
    "America/Santo_Domingo": ["DO", "Santo Domingo"],
    "America/Sao_Paulo": ["BR", "Sao Paulo"],
    "America/Scoresbysund": ["GL", "Scoresbysund"],
    "America/Shiprock": ["US", "Denver"],
    "America/Sitka": ["US", "Sitka"],
    "America/St_Barthelemy": ["BL", "St Barthelemy"],
    "America/St_Johns": ["CA", "St Johns"],
    "America/St_Kitts": ["KN", "St Kitts"],
    "America/St_Lucia": ["LC", "St Lucia"],
    "America/St_Thomas": ["VI", "St Thomas"],
    "America/St_Vincent": ["VC", "St Vincent"],
    "America/Swift_Current": ["CA", "Swift Current"],
    "America/Tegucigalpa": ["HN", "Tegucigalpa"],
    "America/Thule": ["GL", "Thule"],
    "America/Thunder_Bay": ["CA", "Toronto"],
    "America/Tijuana": ["MX", "Tijuana"],
    "America/Toronto": ["CA", "Toronto"],
    "America/Tortola": ["VG", "Tortola"],
    "America/Vancouver": ["CA", "Vancouver"],
    "America/Virgin": ["VI", "St Thomas"],
    "America/Whitehorse": ["CA", "Whitehorse"],
    "America/Winnipeg": ["CA", "Winnipeg"],
    "America/Yakutat": ["US", "Yakutat"],
    "America/Yellowknife": ["CA", "Edmonton"],
    "Antarctica/Casey": ["AQ", "Casey"],
    "Antarctica/Davis": ["AQ", "Davis"],
    "Antarctica/DumontDUrville": ["AQ", "DumontDUrville"],
    "Antarctica/Macquarie": ["AU", "Macquarie"],
    "Antarctica/Mawson": ["AQ", "Mawson"],
    "Antarctica/McMurdo": ["AQ", "McMurdo"],
    "Antarctica/Palmer": ["AQ", "Palmer"],
    "Antarctica/Rothera": ["AQ", "Rothera"],
    "Antarctica/South_Pole": ["AQ", "McMurdo"],
    "Antarctica/Syowa": ["AQ", "Syowa"],
    "Antarctica/Troll": ["AQ", "Troll"],
    "Antarctica/Vostok": ["AQ", "Vostok"],
    "Arctic/Longyearbyen": ["SJ", "Longyearbyen"],
    "Asia/Aden": ["YE", "Aden"],
    "Asia/Almaty": ["KZ", "Almaty"],
    "Asia/Amman": ["JO", "Amman"],
    "Asia/Anadyr": ["RU", "Anadyr"],
    "Asia/Aqtau": ["KZ", "Aqtau"],
    "Asia/Aqtobe": ["KZ", "Aqtobe"],
    "Asia/Ashgabat": ["TM", "Ashgabat"],
    "Asia/Ashkhabad": ["TM", "Ashgabat"],
    "Asia/Atyrau": ["KZ", "Atyrau"],
    "Asia/Baghdad": ["IQ", "Baghdad"],
    "Asia/Bahrain": ["BH", "Bahrain"],
    "Asia/Baku": ["AZ", "Baku"],
    "Asia/Bangkok": ["TH", "Bangkok"],
    "Asia/Barnaul": ["RU", "Barnaul"],
    "Asia/Beirut": ["LB", "Beirut"],
    "Asia/Bishkek": ["KG", "Bishkek"],
    "Asia/Brunei": ["BN", "Brunei"],
    "Asia/Calcutta": ["IN", "Kolkata"],
    "Asia/Chita": ["RU", "Chita"],
    "Asia/Choibalsan": ["MN", "Ulaanbaatar"],
    "Asia/Chongqing": ["CN", "Shanghai"],
    "Asia/Chungking": ["CN", "Shanghai"],
    "Asia/Colombo": ["LK", "Colombo"],
    "Asia/Dacca": ["BD", "Dhaka"],
    "Asia/Damascus": ["SY", "Damascus"],
    "Asia/Dhaka": ["BD", "Dhaka"],
    "Asia/Dili": ["TL", "Dili"],
    "Asia/Dubai": ["AE", "Dubai"],
    "Asia/Dushanbe": ["TJ", "Dushanbe"],
    "Asia/Famagusta": ["CY", "Famagusta"],
    "Asia/Gaza": ["PS", "Gaza"],
    "Asia/Harbin": ["CN", "Shanghai"],
    "Asia/Hebron": ["PS", "Hebron"],
    "Asia/Ho_Chi_Minh": ["VN", "Ho Chi Minh"],
    "Asia/Hong_Kong": ["HK", "Hong Kong"],
    "Asia/Hovd": ["MN", "Hovd"],
    "Asia/Irkutsk": ["RU", "Irkutsk"],
    "Asia/Istanbul": ["TR", "Istanbul"],
    "Asia/Jakarta": ["ID", "Jakarta"],
    "Asia/Jayapura": ["ID", "Jayapura"],
    "Asia/Jerusalem": ["IL", "Jerusalem"],
    "Asia/Kabul": ["AF", "Kabul"],
    "Asia/Kamchatka": ["RU", "Kamchatka"],
    "Asia/Karachi": ["PK", "Karachi"],
    "Asia/Kashgar": ["CN", "Urumqi"],
    "Asia/Kathmandu": ["NP", "Kathmandu"],
    "Asia/Katmandu": ["NP", "Kathmandu"],
    "Asia/Khandyga": ["RU", "Khandyga"],
    "Asia/Kolkata": ["IN", "Kolkata"],
    "Asia/Krasnoyarsk": ["RU", "Krasnoyarsk"],
    "Asia/Kuala_Lumpur": ["MY", "Kuala Lumpur"],
    "Asia/Kuching": ["MY", "Kuching"],
    "Asia/Kuwait": ["KW", "Kuwait"],
    "Asia/Macao": ["MO", "Macau"],
    "Asia/Macau": ["MO", "Macau"],
    "Asia/Magadan": ["RU", "Magadan"],
    "Asia/Makassar": ["ID", "Makassar"],
    "Asia/Manila": ["PH", "Manila"],
    "Asia/Muscat": ["OM", "Muscat"],
    "Asia/Nicosia": ["CY", "Nicosia"],
    "Asia/Novokuznetsk": ["RU", "Novokuznetsk"],
    "Asia/Novosibirsk": ["RU", "Novosibirsk"],
    "Asia/Omsk": ["RU", "Omsk"],
    "Asia/Oral": ["KZ", "Oral"],
    "Asia/Phnom_Penh": ["KH", "Phnom Penh"],
    "Asia/Pontianak": ["ID", "Pontianak"],
    "Asia/Pyongyang": ["KP", "Pyongyang"],
    "Asia/Qatar": ["QA", "Qatar"],
    "Asia/Qostanay": ["KZ", "Qostanay"],
    "Asia/Qyzylorda": ["KZ", "Qyzylorda"],
    "Asia/Rangoon": ["MM", "Yangon"],
    "Asia/Riyadh": ["SA", "Riyadh"],
    "Asia/Saigon": ["VN", "Ho Chi Minh"],
    "Asia/Sakhalin": ["RU", "Sakhalin"],
    "Asia/Samarkand": ["UZ", "Samarkand"],
    "Asia/Seoul": ["KR", "Seoul"],
    "Asia/Shanghai": ["CN", "Shanghai"],
    "Asia/Singapore": ["SG", "Singapore"],
    "Asia/Srednekolymsk": ["RU", "Srednekolymsk"],
    "Asia/Taipei": ["TW", "Taipei"],
    "Asia/Tashkent": ["UZ", "Tashkent"],
    "Asia/Tbilisi": ["GE", "Tbilisi"],
    "Asia/Tehran": ["IR", "Tehran"],
    "Asia/Tel_Aviv": ["IL", "Jerusalem"],
    "Asia/Thimbu": ["BT", "Thimphu"],
    "Asia/Thimphu": ["BT", "Thimphu"],
    "Asia/Tokyo": ["JP", "Tokyo"],
    "Asia/Tomsk": ["RU", "Tomsk"],
    "Asia/Ujung_Pandang": ["ID", "Makassar"],
    "Asia/Ulaanbaatar": ["MN", "Ulaanbaatar"],
    "Asia/Ulan_Bator": ["MN", "Ulaanbaatar"],
    "Asia/Urumqi": ["CN", "Urumqi"],
    "Asia/Ust-Nera": ["RU", "Ust-Nera"],
    "Asia/Vientiane": ["LA", "Vientiane"],
    "Asia/Vladivostok": ["RU", "Vladivostok"],
    "Asia/Yakutsk": ["RU", "Yakutsk"],
    "Asia/Yangon": ["MM", "Yangon"],
    "Asia/Yekaterinburg": ["RU", "Yekaterinburg"],
    "Asia/Yerevan": ["AM", "Yerevan"],
    "Atlantic/Azores": ["PT", "Azores"],
    "Atlantic/Bermuda": ["BM", "Bermuda"],
    "Atlantic/Canary": ["ES", "Canary"],
    "Atlantic/Cape_Verde": ["CV", "Cape Verde"],
    "Atlantic/Faeroe": ["FO", "Faroe"],
    "Atlantic/Faroe": ["FO", "Faroe"],
    "Atlantic/Jan_Mayen": ["NO", "Oslo"],
    "Atlantic/Madeira": ["PT", "Madeira"],
    "Atlantic/Reykjavik": ["IS", "Reykjavik"],
    "Atlantic/South_Georgia": ["GS", "South Georgia"],
    "Atlantic/St_Helena": ["SH", "St Helena"],
    "Atlantic/Stanley": ["FK", "Stanley"],
    "Australia/ACT": ["AU", "Sydney"],
    "Australia/Adelaide": ["AU", "Adelaide"],
    "Australia/Brisbane": ["AU", "Brisbane"],
    "Australia/Broken_Hill": ["AU", "Broken Hill"],
    "Australia/Canberra": ["AU", "Sydney"],
    "Australia/Currie": ["AU", "Hobart"],
    "Australia/Darwin": ["AU", "Darwin"],
    "Australia/Eucla": ["AU", "Eucla"],
    "Australia/Hobart": ["AU", "Hobart"],
    "Australia/LHI": ["AU", "Lord Howe"],
    "Australia/Lindeman": ["AU", "Lindeman"],
    "Australia/Lord_Howe": ["AU", "Lord Howe"],
    "Australia/Melbourne": ["AU", "Melbourne"],
    "Australia/North": ["AU", "Darwin"],
    "Australia/NSW": ["AU", "Sydney"],
    "Australia/Perth": ["AU", "Perth"],
    "Australia/Queensland": ["AU", "Brisbane"],
    "Australia/South": ["AU", "Adelaide"],
    "Australia/Sydney": ["AU", "Sydney"],
    "Australia/Tasmania": ["AU", "Hobart"],
    "Australia/Victoria": ["AU", "Melbourne"],
    "Australia/West": ["AU", "Perth"],
    "Australia/Yancowinna": ["AU", "Broken Hill"],
    "Brazil/Acre": ["BR", "Rio Branco"],
    "Brazil/DeNoronha": ["BR", "Noronha"],
    "Brazil/East": ["BR", "Sao Paulo"],
    "Brazil/West": ["BR", "Manaus"],
    "Canada/Atlantic": ["CA", "Halifax"],
    "Canada/Central": ["CA", "Winnipeg"],
    "Canada/Eastern": ["CA", "Toronto"],
    "Canada/Mountain": ["CA", "Edmonton"],
    "Canada/Newfoundland": ["CA", "St Johns"],
    "Canada/Pacific": ["CA", "Vancouver"],
    "Canada/Saskatchewan": ["CA", "Regina"],
    "Canada/Yukon": ["CA", "Whitehorse"],
    "Chile/Continental": ["CL", "Santiago"],
    "Chile/EasterIsland": ["CL", "Easter"],
    "Europe/Amsterdam": ["NL", "Amsterdam"],
    "Europe/Andorra": ["AD", "Andorra"],
    "Europe/Astrakhan": ["RU", "Astrakhan"],
    "Europe/Athens": ["GR", "Athens"],
    "Europe/Belfast": ["GB", "London"],
    "Europe/Belgrade": ["RS", "Belgrade"],
    "Europe/Berlin": ["DE", "Berlin"],
    "Europe/Bratislava": ["SK", "Bratislava"],
    "Europe/Brussels": ["BE", "Brussels"],
    "Europe/Bucharest": ["RO", "Bucharest"],
    "Europe/Budapest": ["HU", "Budapest"],
    "Europe/Busingen": ["DE", "Busingen"],
    "Europe/Chisinau": ["MD", "Chisinau"],
    "Europe/Copenhagen": ["DK", "Copenhagen"],
    "Europe/Dublin": ["IE", "Dublin"],
    "Europe/Gibraltar": ["GI", "Gibraltar"],
    "Europe/Guernsey": ["GG", "Guernsey"],
    "Europe/Helsinki": ["FI", "Helsinki"],
    "Europe/Isle_of_Man": ["IM", "Isle of Man"],
    "Europe/Istanbul": ["TR", "Istanbul"],
    "Europe/Jersey": ["JE", "Jersey"],
    "Europe/Kaliningrad": ["RU", "Kaliningrad"],
    "Europe/Kiev": ["UA", "Kyiv"],
    "Europe/Kirov": ["RU", "Kirov"],
    "Europe/Kyiv": ["UA", "Kyiv"],
    "Europe/Lisbon": ["PT", "Lisbon"],
    "Europe/Ljubljana": ["SI", "Ljubljana"],
    "Europe/London": ["GB", "London"],
    "Europe/Luxembourg": ["LU", "Luxembourg"],
    "Europe/Madrid": ["ES", "Madrid"],
    "Europe/Malta": ["MT", "Malta"],
    "Europe/Mariehamn": ["AX", "Mariehamn"],
    "Europe/Minsk": ["BY", "Minsk"],
    "Europe/Monaco": ["MC", "Monaco"],
    "Europe/Moscow": ["RU", "Moscow"],
    "Europe/Nicosia": ["CY", "Nicosia"],
    "Europe/Oslo": ["NO", "Oslo"],
    "Europe/Paris": ["FR", "Paris"],
    "Europe/Podgorica": ["ME", "Podgorica"],
    "Europe/Prague": ["CZ", "Prague"],
    "Europe/Riga": ["LV", "Riga"],
    "Europe/Rome": ["IT", "Rome"],
    "Europe/Samara": ["RU", "Samara"],
    "Europe/San_Marino": ["SM", "San Marino"],
    "Europe/Sarajevo": ["BA", "Sarajevo"],
    "Europe/Saratov": ["RU", "Saratov"],
    "Europe/Simferopol": ["UA", "Simferopol"],
    "Europe/Skopje": ["MK", "Skopje"],
    "Europe/Sofia": ["BG", "Sofia"],
    "Europe/Stockholm": ["SE", "Stockholm"],
    "Europe/Tallinn": ["EE", "Tallinn"],
    "Europe/Tirane": ["AL", "Tirane"],
    "Europe/Tiraspol": ["MD", "Chisinau"],
    "Europe/Ulyanovsk": ["RU", "Ulyanovsk"],
    "Europe/Uzhgorod": ["UA", "Kyiv"],
    "Europe/Vaduz": ["LI", "Vaduz"],
    "Europe/Vatican": ["VA", "Vatican"],
    "Europe/Vienna": ["AT", "Vienna"],
    "Europe/Vilnius": ["LT", "Vilnius"],
    "Europe/Volgograd": ["RU", "Volgograd"],
    "Europe/Warsaw": ["PL", "Warsaw"],
    "Europe/Zagreb": ["HR", "Zagreb"],
    "Europe/Zaporozhye": ["UA", "Kyiv"],
    "Europe/Zurich": ["CH", "Zurich"],
    "Indian/Antananarivo": ["MG", "Antananarivo"],
    "Indian/Chagos": ["IO", "Chagos"],
    "Indian/Christmas": ["CX", "Christmas"],
    "Indian/Cocos": ["CC", "Cocos"],
    "Indian/Comoro": ["KM", "Comoro"],
    "Indian/Kerguelen": ["TF", "Kerguelen"],
    "Indian/Mahe": ["SC", "Mahe"],
    "Indian/Maldives": ["MV", "Maldives"],
    "Indian/Mauritius": ["MU", "Mauritius"],
    "Indian/Mayotte": ["YT", "Mayotte"],
    "Indian/Reunion": ["RE", "Reunion"],
    "Mexico/BajaNorte": ["MX", "Tijuana"],
    "Mexico/BajaSur": ["MX", "Mazatlan"],
    "Mexico/General": ["MX", "Mexico City"],
    "Pacific/Apia": ["WS", "Apia"],
    "Pacific/Auckland": ["NZ", "Auckland"],
    "Pacific/Bougainville": ["PG", "Bougainville"],
    "Pacific/Chatham": ["NZ", "Chatham"],
    "Pacific/Chuuk": ["FM", "Chuuk"],
    "Pacific/Easter": ["CL", "Easter"],
    "Pacific/Efate": ["VU", "Efate"],
    "Pacific/Enderbury": ["KI", "Kanton"],
    "Pacific/Fakaofo": ["TK", "Fakaofo"],
    "Pacific/Fiji": ["FJ", "Fiji"],
    "Pacific/Funafuti": ["TV", "Funafuti"],
    "Pacific/Galapagos": ["EC", "Galapagos"],
    "Pacific/Gambier": ["PF", "Gambier"],
    "Pacific/Guadalcanal": ["SB", "Guadalcanal"],
    "Pacific/Guam": ["GU", "Guam"],
    "Pacific/Honolulu": ["US", "Honolulu"],
    "Pacific/Johnston": ["US", "Honolulu"],
    "Pacific/Kanton": ["KI", "Kanton"],
    "Pacific/Kiritimati": ["KI", "Kiritimati"],
    "Pacific/Kosrae": ["FM", "Kosrae"],
    "Pacific/Kwajalein": ["MH", "Kwajalein"],
    "Pacific/Majuro": ["MH", "Majuro"],
    "Pacific/Marquesas": ["PF", "Marquesas"],
    "Pacific/Midway": ["UM", "Midway"],
    "Pacific/Nauru": ["NR", "Nauru"],
    "Pacific/Niue": ["NU", "Niue"],
    "Pacific/Norfolk": ["NF", "Norfolk"],
    "Pacific/Noumea": ["NC", "Noumea"],
    "Pacific/Pago_Pago": ["AS", "Pago Pago"],
    "Pacific/Palau": ["PW", "Palau"],
    "Pacific/Pitcairn": ["PN", "Pitcairn"],
    "Pacific/Pohnpei": ["FM", "Pohnpei"],
    "Pacific/Ponape": ["FM", "Pohnpei"],
    "Pacific/Port_Moresby": ["PG", "Port Moresby"],
    "Pacific/Rarotonga": ["CK", "Rarotonga"],
    "Pacific/Saipan": ["MP", "Saipan"],
    "Pacific/Samoa": ["AS", "Pago Pago"],
    "Pacific/Tahiti": ["PF", "Tahiti"],
    "Pacific/Tarawa": ["KI", "Tarawa"],
    "Pacific/Tongatapu": ["TO", "Tongatapu"],
    "Pacific/Truk": ["FM", "Chuuk"],
    "Pacific/Wake": ["UM", "Wake"],
    "Pacific/Wallis": ["WF", "Wallis"],
    "Pacific/Yap": ["FM", "Chuuk"],
    "US/Alaska": ["US", "Anchorage"],
    "US/Aleutian": ["US", "Adak"],
    "US/Arizona": ["US", "Phoenix"],
    "US/Central": ["US", "Chicago"],
    "US/East-Indiana": ["US", "Indiana / Indianapolis"],
    "US/Eastern": ["US", "New York"],
    "US/Hawaii": ["US", "Honolulu"],
    "US/Indiana-Starke": ["US", "Indiana / Knox"],
    "US/Michigan": ["US", "Detroit"],
    "US/Mountain": ["US", "Denver"],
    "US/Pacific": ["US", "Los Angeles"],
    "US/Samoa": ["AS", "Pago Pago"],
};
